name: stac
channels:
  - conda-forge
  - defaults
dependencies:
  - affine=2.4.0
  - annotated-types=0.6.0
  - anyio=4.2.0
  - appnope=0.1.3
  - argon2-cffi=21.3.0
  - argon2-cffi-bindings
  - asttokens=2.0.5
  - async-lru=2.0.4
  - attrs=23.1.0
  - aws-c-auth=0.7.22
  - aws-c-cal=0.6.14
  - aws-c-common=0.9.19
  - aws-c-compression=0.2.18
  - aws-c-event-stream=0.4.2
  - aws-c-http=0.8.1
  - aws-c-io=0.14.8
  - aws-c-mqtt=0.10.4
  - aws-c-s3=0.5.9
#  - aws-c-sdkutil=
  - aws-checksums=0.1.18
  - aws-crt-cpp=0.26.9
  - aws-sdk-cpp=1.11.329
  - azure-core-cpp=1.11.1
  - azure-identity-cpp=1.6.0
  - azure-storage-blobs-cpp
  - azure-storage-common-cpp
  - babel=2.11.0
  - beautifulsoup4=4.12.2
  - blas=1.0=openblas
  - bleach=4.1.0
  - blosc=1.21.5
  - boost-cpp=1.82.0
  - bottleneck=1.3.7
  - branca=0.6.0
  - brotli=1.0.9
  - brotli-bin=1.0.9
  - brotli-python=1.0.9
  - bzip2=1.0.8
  - c-ares=1.28.1
  - ca-certificates=2024.6.2
  - cairo=1.18.0
  - certifi=2024.6.2
  - cffi=1.16.0
  - cfitsio=4.4.0
  - charset-normalizer=2.0.4
  - click=8.1.7
  - click-plugins=1.1.1
  - comm=0.2.1
  - contourpy=1.2.0
  - cycler=0.11.0
  - cyrus-sasl=2.1.27
  - debugpy=1.6.7
  - decorator=5.1.1
  - defusedxml=0.7.1
  - executing=0.8.3
  - expat=2.6.2
  - fiona=1.9.6
  - fmt=10.2.1
  - folium=0.14.0
#  - font-ttf-dejavu-sans-mono.37
#  - font-ttf-inconsolata=3.000
#  - font-ttf-source-code-pro=2.038
#  - font-ttf-ubuntu=0.83
  - fontconfig=2.14.2
  - fonts-conda-ecosystem=1=0
  - fonts-conda-forge=1=0
  - fonttools=4.51.0
  - freetype=2.12.1
  - freexl=2.0.0
  - gdal=3.8.5
  - geojson=3.1.0
  - geopandas=0.14.2
  - geopandas-base=0.14.2
  - geos=3.12.1
  - geotiff=1.7.3
  - gettext=0.22.5
  - gettext-tools=0.22.5
  - giflib=5.2.2
  - glib=2.80.2
  - glib-tools=2.80.2
  - gst-plugins-base.24.4
  - gstreamer=1.24.4
  - hdf4=4.2.15
  - hdf5=1.14.3
  - icu=73.2
  - idna=3.7
  - ipykernel=6.28.0
  - ipython=8.20.0
  - ipywidgets=8.1.2
  - jedi=0.18.1
  - jinja2=3.1.4
  - joblib=1.4.0
  - json-c=0.17
  - json5=0.9.6
  - jsonschema=4.19.2
  - jsonschema-specifications=2023.7.1
  - jupyter=1.0.0
  - jupyter-lsp=2.2.0
  - jupyter_client=8.6.0
  - jupyter_console=6.6.3
  - jupyter_core=5.5.0
  - jupyter_events=0.8.0
  - jupyter_server=2.10.0
  - jupyter_server_terminals=0.4.4
  - jupyterlab=4.0.11
  - jupyterlab_pygments=0.1.2
  - jupyterlab_server=2.25.1
  - jupyterlab_widgets=3.0.10
  - kealib=1.5.3
  - kiwisolver=1.4.4
  - krb5=1.21.2
  - lcms2=2.16
  - lerc=4.0.0
  - libabseil=20240116.2
  - libaec=1.1.3
  - libarchive=3.7.4
  - libasprintf=0.22.5
  - libasprintf-devel=0.22.5
  - libblas=3.9.0
  - libboost=1.82.0
  - libboost-headers=1.82.0
  - libbrotlicommon=1.0.9
  - libbrotlidec=1.0.9
  - libbrotlienc=1.0.9
  - libcblas=3.9.0
  - libclang=18.1.6
  - libclang-cpp15=15.0.7
  - libclang13=18.1.6
  - libcrc32c=1.1.2
  - libcurl=8.8.0
  - libcxx=17.0.6
  - libdeflate=1.20
  - libedit=3.1.20230828
  - libev=4.33
  - libevent=2.1.12
  - libexpat=2.6.2
  - libffi=3.4.4
  - libgdal=3.8.5
  - libgettextpo=0.22.5
  - libgettextpo-devel=0.22.5
  - libgfortran=5.0.0
  - libgfortran5=13.2.0
  - libglib=2.80.2
  - libgoogle-cloud
  - libgoogle-cloud-storage=2.24.0
  - libgrpc=1.62.2
  - libiconv=1.17
#  - libintl=0.22.5
#  - libintl-devel=0.22.5
  - libjpeg-turbo=3.0.0
  - libkml=1.3.0
  - liblapack=3.9.0
  - libllvm14=14.0.6
  - libllvm15=15.0.7
  - libllvm18=18.1.6
  - libnetcdf=4.9.2
  - libnghttp2=1.58.0
  - libntlm=1.4
  - libogg=1.3.4
  - libopenblas=0.3.23
  - libopus=1.3.1
  - libpng=1.6.43
  - libpq=16.3
  - libprotobuf=4.25.3
  - libre2-11=2023.09.01
  - librttopo=1.1.0
  - libsodium=1.0.18
  - libspatialindex=1.9.3
  - libspatialite=5.1.0
  - libsqlite=3.45.3
  - libssh2=1.11.0
  - libtiff=4.6.0
  - libvorbis=1.3.7
  - libwebp-base=1.4.0
  - libxcb=1.15
  - libxml2=2.12.7
  - libzip=1.10.1
  - libzlib=1.2.13
  - llvm-openmp=14.0.6
  - lz4-c=1.9.4
  - lzo=2.10
  - macports-legacy-support=1.2.4
  - mapclassify=2.5.0
  - markupsafe=2.1.3
  - matplotlib-base=3.8.4
  - matplotlib-inline=0.1.6
  - minizip=4.0.3
  - mistune=2.0.4
  - morecantile=5.3.0
  - mysql=8.3.0
  - mysql-client=8.3.0
  - mysql-common=8.3.0
  - mysql-devel=8.3.0
  - mysql-libs=8.3.0
  - mysql-server=8.3.0
  - nbclient=0.8.0
  - nbconvert=7.10.0
  - nbformat=5.9.2
  - ncurses=6.4
  - nest-asyncio=1.6.0
  - networkx=3.1
  - notebook=7.0.8
  - notebook-shim=0.2.3
  - nspr=4.35
  - nss=3.100
  - numexpr=2.8.7
  - numpy=1.26.4
  - openjpeg=2.5.2
  - openssl=3.3.1
  - overrides=7.4.0
  - packaging=23.2
  - pandas=2.2.1
  - pandocfilters=1.5.0
  - parso=0.8.3
  - pcre2=10.43
  - pexpect=4.8.0
  - pillow=10.3.0
  - pip=24.0
  - pixman=0.40.0
  - planetary-computer=1.0.0
  - platformdirs=3.10.0
  - ply=3.11
  - poppler=24.04.0
  - poppler-data=0.4.12
  - postgresql=16.3
  - proj=9.4.0
  - prometheus_client=0.14.1
  - prompt-toolkit=3.0.43
  - prompt_toolkit=3.0.43
  - psutil=5.9.0
  - pthread-stubs=0.4
  - ptyprocess=0.7.0
  - pure_eval=0.2.2
  - pybind11-abi=5
  - pycparser=2.21
  - pydantic=2.5.3
  - pydantic-core=2.14.6
  - pygments=2.15.1
  - pyproj=3.6.1
  - pyqt=5.15.10
  - pyqt5-sip=12.13.0
  - pysocks=1.7.1
  - pystac=1.10.1
  - pystac-client=0.8.1
  - python=3.12.2
  - python-dateutil=2.9.0post0
  - python-dotenv=0.21.0
  - python-fastjsonschema=2.16.2
  - python-json-logger=2.0.7
  - python-tzdata=2023.3
  - python_abi=3.12
  - pytz=2024.1
  - pyyaml=6.0.1
  - pyzmq=25.1.2
  - qhull=2020.2
  - qt-main=5.15.8
  - qtconsole=5.5.1
  - qtpy=2.4.1
  - rasterio=1.3.10
  - re2=2023.09.01
  - readline=8.2
  - referencing=0.30.2
  - requests=2.32.2
  - rfc3339-validator=0.1.4
  - rfc3986-validator=0.1.1
  - rio-cogeo=5.3.0
  - rpds-py=0.10.6
  - rtree=1.0.1
  - scikit-learn=1.4.2
  - scipy=1.13.0
  - send2trash=1.8.2
  - setuptools=69.5.1
  - shapely=2.0.4
  - sip=6.7.12
  - six=1.16.0
  - snappy=1.2.0
  - sniffio=1.3.0
  - snuggs=1.4.7
  - soupsieve=2.5
  - spdlog=1.13.0
  - sqlite=3.45.3
  - stack_data=0.2.0
  - terminado=0.17.1
  - threadpoolctl
  - tiledb=2.23.0
  - tinycss2=1.2.1
  - tk=8.6.14
  - tornado=6.3.3
  - traitlets=5.7.1
  - typing-extensions=4.11.0
  - typing_extensions=4.11.0
  - tzcode=2024a
  - tzdata=2024a
  - unicodedata2
  - uriparser=0.9.8
  - urllib3=2.2.1
  - wcwidth=0.2.5
  - webencodings=0.5.1
  - websocket-client=1.8.0
  - wheel=0.43.0
  - widgetsnbextension=4.0.10
  - xerces-c=3.2.5
  - xorg-libxau=1.0.11
  - xorg-libxdmcp=1.1.3
  - xyzservices=2022.9.0
  - xz=5.4.6
  - yaml=0.2.5
  - zeromq=4.3.5
  - zlib=1.2.13
  - zstd=1.5.6
  - pip:
      - cligj==0.7.2
      - iniconfig==2.0.0
      - pluggy==1.5.0
      - pyparsing==3.1.2
      - pytest==8.2.2

