name: CI

on:
  push:
    branches:
      - main
      - stac-cli
  pull_request:
    branches:
      - main
jobs:
  test:
    name: test
    runs-on: ${{ matrix.os }}
    continue-on-error: ${{ matrix.experimental }}
    strategy:
      fail-fast: true
      matrix:
        python-version:
          - "3.12.2"
        os:
          - ubuntu-latest
        experimental:
          - false
        include:
          - python-version: "3.12.2"
            os: ubuntu-latest
            experimental: true
    steps:
      - uses: actions/checkout@v3
        with:
          persist-credentials: false
          fetch-depth: 0
      - uses: conda-incubator/setup-miniconda@v2
        with:
          channels: conda-forge,defaults
          channel-priority: true
          python-version: ${{ matrix.python-version }}
          auto-update-conda: true

      - name: Install dependencies
        shell: bash -l {0}
        run: |
          conda env create --name stac --file=environment-test.yaml
          conda activate stac

      - name: Lint
        run: |
          pip install pre-commit
          pre-commit run --all-files

      - name: Run test suite
        shell: bash -l {0}
        run: |
          conda activate stac
          python -m pytest

      - name: Run and test CLI
        shell: bash -l {0}
        run: |
          conda activate stac
          python main.py -b=10.251789,48.268455,10.511341,48.366400 -t=2023-04-20/2023-04-23 -c=landsat-c2-l2 -a=red

