name: Continuous integration
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  python-matrix:
    name: python-matrix
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.7, 3.8, 3.9, 3.10, 3.11]

    steps:

      
      # - name: Setup python
      - uses: actions/setup-python@v4

      # - with:
      #   python-version: ${{ matrix.python-version }}
      
      # - name: Setup test dependencies
      - run: python -m pip install pytest 
      
      # - name: Run Tests
      - run: pytest




 