name: CI

on:
  push:
    branches:
      - main
      - stac-cli
  pull_request:
    branches:
      - main
jobs:
  test:
    name: test
    runs-on: ${{ matrix.os }}
    continue-on-error: ${{ matrix.experimental }}
    strategy:
      fail-fast: true
      matrix:
        python-version:
          - "3.12.2"
        os:
          - ubuntu-latest
        experimental:
          - false
        include:
          - python-version: "3.12.2"
            os: ubuntu-latest
            experimental: true
    steps:



      - uses: actions/checkout@v3
      - name: Install dependencies
        run: |
              sudo apt-add-repository ppa:ubuntugis/ubuntugis-unstable
              sudo apt-get update
              sudo apt-get install gdal-bin libgdal-dev
              GDAL=gdal-config --version
              echo "Hello, $gdal"
              pip install GDAL==3.2.3

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install -r requirements-test.txt
          pip install -e ".[validation]"

      - name: Execute test suite
        run: ./scripts/test
        shell: bash



      - name: Execute test suite
        run: ./scripts/test
        env:
          CHECK_COVERAGE: true


  lint:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        python-version:
          - "3.12.2"
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}


      - name: Linters and mypy type
        run: |
          pip install pytest
          pip install -r requirements-test.txt
          pytest

