name: Continuous integration
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  codecov:
    name: codecov
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Excecute tests
        run: echo "test"
  